name: Agent Workflow

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run TypeScript compiler check
        run: npx tsc --noEmit

      - name: Run unit tests
        run: npm run test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start dev server
        run: npm run dev & npx wait-on http://localhost:5173

      - name: Run E2E tests
        run: npm run test:e2e:ci

      - name: Run visual regression tests
        run: npx playwright test --config=playwright.visual.config.ts

      - name: Upload visual test artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: visual-test-results
          path: |
            e2e/visual-tests/snapshots
            e2e/visual-tests/diffs
            e2e/visual-tests/results

      - name: Upload E2E test screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-screenshots
          path: e2e-screenshots/
          retention-days: 7

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-reports
          path: |
            playwright-report/
            coverage/
          retention-days: 7

  build:
    runs-on: ubuntu-latest
    needs: lint-and-test

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7
